# Dados de conexão MySQL
mysql:
  host: "localhost:3306"
  database: ""
  user: ""
  password: ""

# Formatações de números grandes
format:
  # Usar sistema de formatação com sufixo
  use: true
  # Valor mínimo para formatar com sufixo
  minValue: 1000.0
  # Lista de sufixos (Pode adicionar quantos quiser)
  suffixes:
    - ""
    - "K"
    - "M"
    - "B"
    - "T"
    - "Q"
    - "QQ"
    - "S"
    - "SS"
    - "OC"
    - "N"
    - "D"
    - "UN"
    - "DD"
    - "TR"
    - "QN"
    - "QD"
    - "SD"
    - "SPD"
    - "OD"
    - "ND"
    - "VG"